server:
 port: 8111

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: 127.0.0.1
    port: 6379
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: aaa
      auto-offset-reset: earliest
